### ISSUE TITLE
[bug]: Factory Reset does not "delete existing data on disk"

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/start-os#2553] opened 2024-01-22 17:30 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

x86_64 (Server One)

### StartOS Version

0.3.5.1 (nonfree)

### Client OS

Linux

### Client OS Version

Debian 12

### Browser

Firefox

### Browser Version

121

### Current Behavior

On the Install Type screen, there are two options:
* Re-Install StartOS ["Will preserve existing StartOS data"]
* Factory Reset ["Will delete existing data on disk"]

When selecting Factory Reset, the Data partition is preserved.  The result is that anyone who selects "Factory Reset" at install time, after rebooting to the setup wizard, is still presented with the option to "Use existing drive" (See reproduction screenshots below).

Is this intentional?
If so I don't see the reason to offer both "Re-install StartOS" and "Factory Reset"
If not, we have a bug.

### Expected Behavior

I am expecting "Factory Reset" to wipe all data (including service data from the user data partition) from the disk.  The data is preserved (See screenshots below).

### Steps to Reproduce

1. Boot USB installation media (v0351 nonfree in this case) and select the disk:
![image](https://github.com/Start9Labs/start-os/assets/106188942/3ce5f064-de8e-4a47-a23d-ed7557dbb3e2)

2. Select "Factory Reset" as the install type:
![image](https://github.com/Start9Labs/start-os/assets/106188942/1e1481d2-e94c-401d-b929-8be4b01aa36e)

3. A warning appears stating "This action will COMPLETELY erase the disk __DISK_NAME___":
![image](https://github.com/Start9Labs/start-os/assets/106188942/0012f695-979f-4830-878e-8418b3e76db8)

4. The UI indicates success.  Click REBOOT:
![image](https://github.com/Start9Labs/start-os/assets/106188942/93a3474c-a40e-460e-8001-ab99a7ca7f7b)

5. Remove the USB installation media and reboot.  StartOS setup wizard appears.  Choose Recover:
![image](https://github.com/Start9Labs/start-os/assets/106188942/741627e4-bc29-44b1-994a-bec8169dcc19)

6. Under Recover Options, select Use Existing Drive:
![image](https://github.com/Start9Labs/start-os/assets/106188942/95057260-1df0-4447-aa06-87d7b051aa64)

7. The disk that was supposedly wiped appears as an existing drive able to be used:
![image](https://github.com/Start9Labs/start-os/assets/106188942/642605c9-4407-4843-b965-a522f46f1a84)

8. Select the drive and it will restore your old install.

**Comment by dr-bonez** [comment] 2024-01-23 21:21
Duplicate of #2162

**Closed** 2024-01-23 21:22 UTC
Labels: Bug, embassyd
