### ISSUE TITLE
[bug]: tor.rs restarts tor after slow progress

### ISSUE THREAD

**Issue by slaroy** [Start9Labs/start-os#2349] opened 2023-07-12 21:34 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

VM in TrueNAS scale, 8GB RAM, 2TB HDD

### StartOS Version

0.3.4~3

### Client OS

Windows

### Client OS Version

Windows 10

### Browser

Firefox

### Browser Version

115.0.2

### Current Behavior

embassy::net::tor::torctl monitors progress, and restarts tor if no bootstrapping progress after 30 seconds. For some reason, maybe due to ISP or VM configuration (?), my tor startup is really slow, and tor gets stuck in an endless reboot cycle without ever fully connecting. It did work for the first 12 hours, then stopped. Re-installing the OS and re-imaging the VM did not resolve.

OS Logs:

```
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  0: embassy::net::tor::torctl
  at src/net/tor.rs:255
 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
 Run with RUST_BACKTRACE=full to include source snippets., kind: Tor, revision: None }
 2023-07-12T07:47:36.331770Z INFO torctl: embassy::net::tor: Tor is started
 2023-07-12T07:48:07.381667Z ERROR embassy::net::tor: Tor Daemon Error: Tor stuck bootstrapping at 5%: Restarting tor
 2023-07-12T07:48:07.381695Z DEBUG embassy::net::tor: Error { source:
  0: Tor stuck bootstrapping at 5%
 Location:
  src/net/tor.rs:359
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

TOR Logs:

```
systemd[1]: Starting tor@default.service - Anonymizing overlay network for TCP...

tor[10316]: Jul 11 23:53:52.359 [notice] Tor 0.4.7.13 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.>

tor[10316]: Jul 11 23:53:52.359 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https:/>

tor[10316]: Jul 11 23:53:52.359 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".

tor[10316]: Jul 11 23:53:52.359 [notice] Read configuration file "/etc/tor/torrc".

tor[10316]: Configuration was valid

tor[10317]: Jul 11 23:53:52.438 [notice] Tor 0.4.7.13 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.>

tor[10317]: Jul 11 23:53:52.438 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https:/>

tor[10317]: Jul 11 23:53:52.438 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".

tor[10317]: Jul 11 23:53:52.438 [notice] Read configuration file "/etc/tor/torrc".

tor[10317]: Jul 11 23:53:52.439 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people>

tor[10317]: Jul 11 23:53:52.439 [notice] Opening Socks listener on 0.0.0.0:9050

tor[10317]: Jul 11 23:53:52.439 [notice] Opened Socks listener connection (ready) on 0.0.0.0:9050

tor[10317]: Jul 11 23:53:52.439 [notice] Opening Control listener on 127.0.0.1:9051

tor[10317]: Jul 11 23:53:52.439 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051

Tor[10317]: We compiled with OpenSSL 101010ef: OpenSSL 1.1.1n  15 Mar 2022 and we are running with OpenSSL 10101>

Tor[10317]: Tor 0.4.7.13 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma 5.2.>

Tor[10317]: Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/s>

Tor[10317]: Read configuration file "/usr/share/tor/tor-service-defaults-torrc".

Tor[10317]: Read configuration file "/etc/tor/torrc".

Tor[10317]: You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find>

Tor[10317]: Opening Socks listener on 0.0.0.0:9050

Tor[10317]: Opened Socks listener connection (ready) on 0.0.0.0:9050

Tor[10317]: Opening Control listener on 127.0.0.1:9051

Tor[10317]: Opened Control listener connection (ready) on 127.0.0.1:9051

Tor[10317]: Parsing GEOIP IPv4 file /usr/share/tor/geoip.

Tor[10317]: Parsing GEOIP IPv6 file /usr/share/tor/geoip6.

Tor[10317]: Bootstrapped 0% (starting): Starting

systemd[1]: Started tor@default.service - Anonymizing overlay network for TCP.

Tor[10317]: Starting with guard context "default"

Tor[10317]: Signaled readiness to systemd\

Tor[10317]: New control connection opened from 127.0.0.1.

Tor[10317]: Opening Control listener on /run/tor/control

Tor[10317]: Opened Control listener connection (ready) on /run/tor/control

Tor[10317]: Bootstrapped 5% (conn): Connecting to a relay

Tor[10317]: Interrupt: exiting cleanly.

systemd[1]: Stopping tor@default.service - Anonymizing overlay network for TCP...

systemd[1]: tor@default.service: Deactivated successfully.

systemd[1]: Stopped tor@default.service - Anonymizing overlay network for TCP.

systemd[1]: Starting tor@default.service - Anonymizing overlay network for TCP...
```

### Expected Behavior

A configurable, or exponential backoff on the restart time (up to some limit), to allow tor enough time to connect. Also, more log messages to explain / troubleshoot behaviour.

### Steps to Reproduce

1. Install OS 
2. tor fails to come up
3. view logs

**Comment by kn0wmad** [comment] 2023-07-13 21:01
@slaroy Can you detail your network setup please?  We just had a user with the same issue, which ended up being caused by a network extender.

**Comment by slaroy** [comment] 2023-07-14 19:26
My server is connected to my WiFi base station via a range extender, and it turns out that this works for a single host. With more than one host hanging off the extender it stopped working, probably when the DHCP lease renewed. I suspect there was some conflict due to DHCP reservations, or ARP conflicts. I haven't resolved the issue yet, but the problem appears to be on my end. Since the VM received a DHCP address, I assumed the network was OK, but it turns out I couldn't even ping the gateway!

All I could tell from the StartOS GUI was that TOR wasn't working, and there was no other way to validate that there was internet access.


<img width="750" alt="LAN_RE" src="https://github.com/Start9Labs/start-os/assets/89828415/16212df8-b68b-4376-a629-4ba32dd93bf7">

**Comment by kn0wmad** [comment] 2023-07-14 20:23
Thanks for the update.  We highly recommend giving your server direct ethernet access to your router if at all possible.  Closing as unrelated to the OS.

**Closed by kn0wmad** 2023-07-14 20:23 UTC
Labels: Bug

**Comment by renatomarcio** [comment] 2024-07-18 01:14
Same problem here. I am running SartOS on a proxmox VM, connected directly to the router (pfSense). OS works fine, updates, services are all up. I can reach the StartOS using its lan address, but onion will not work. Reseted TOR, rebuid the system. Nothing seems to work.

**Comment by esackbauer** [comment] 2026-04-03 18:19
I have a 2TB SSD so that wasnt the problem. I simply upgraded to StartOS 0.4.0 and all my problems went away.
