### ISSUE TITLE
[feat]: Ability to use 2 or more storage devices

### ISSUE THREAD

**Issue by techrivertree** [Start9Labs/start-os#2384] opened 2023-08-04 02:00 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

At the current time StartOS only allows one storage device. I would like to install bitcoin core. The ledger is almost 500GB so I would like to have it installed on a secondary storage device

### Describe the Use Case

Backups, more storage, ability to install bitcoin ledger on a larger storage device, etc.

### Describe Preferred Solution

Allow StartOS to recognize secondary storage devices.

### Describe Alternatives

None.

### Anything else?

Thanks to the devs who developed StartOS, it just needs a little improving.

**Comment by kn0wmad** [comment] 2023-08-07 04:13
Closing as a duplicate of #2060 - please search issues before creating new ones to ensure it has not already been requested

**Closed by kn0wmad** 2023-08-07 04:13 UTC
Labels: Enhancement
