### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Wileynesslessness** [Start9Labs/start-os#2288] opened 2023-05-30 21:02 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### StartOS Version

v0.3..4rev-1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 22.04.2 LTS

### Browser

Firefox

### Browser Version

113.0.2 (64-bit)

### Current Behavior

Following https://github.com/Start9Labs/service-pipeline to sideload a service. During Embassy-sdk portion of guide: 

git clone -b latest --recursive https://github.com/Start9Labs/embassy-os.git && cd embassy-os/backend && ./install-sdk.sh

runs until encountering : 

  Installing embassy-os v0.3.4-rev.1 (/home/xxx/embassy-os/backend/embassy-os/backend/embassy-os/backend/embassy-os/backend)
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to create temporary file '/home/xxx/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects/pack/pack_git2_0bcd89144330e8ef': Permission denied; class=Os (2)
warning: spurious network error (1 tries remaining): failed to create temporary file '/home/xxx/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects/pack/pack_git2_04bdff7dcdc6ea40': Permission denied; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

### Expected Behavior

I'm a noob, fuck if i know

### Steps to Reproduce

Follow steps of the guide?

### Anything else?

Not sure i'm even in the right forum for this, maybe i should be asking on the telegram group.

**Comment by kn0wmad** [comment] 2023-05-31 02:34
You do not have adequate permissions on your `.cargo` directory.  Please come into one of our Dev channels on Telegram or Matrix for additional assistance.  Closing as an environmental issue, not a bug.

**Closed by kn0wmad** 2023-05-31 02:34 UTC
Labels: Bug, Needs Triage
