### ISSUE TITLE
[bug]: Pressing "Update" on the Updates page makes all versions on all registries display a spinner

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/start-os#2550] opened 2024-01-10 01:02 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Server Pure

### StartOS Version

0.3.5.1

### Client OS

Linux

### Client OS Version

Debian 12

### Browser

Firefox

### Browser Version

121.0

### Current Behavior

Pressing "Update" on NextCloud 26.0.8.1 from Alpha starts updating NextCloud from Alpha, but also the spinner indicating an update spins on all available versions of NextCloud:
![image](https://github.com/Start9Labs/start-os/assets/106188942/af2b419c-ff3b-449b-a1ff-72eb7be6a626)

### Expected Behavior

I expect only the version of NextCloud that I clicked on to Update and indicate that it's updating

### Steps to Reproduce

1. Enable dev tools by clicking System > MANAGE header 5x
2. Go to the updates tab and see you have 2 nextcloud updates available **Beta: 26.0.8** and **Alpha: 26.0.8.1**
3. Click Update on the Alpha version
4. See that Both NextCloud versions seem to indicate that they're downloading and installing.
5. I verified that only the intended version of NextCloud is the one installing:
![image](https://github.com/Start9Labs/start-os/assets/106188942/71dfbb4a-3814-46db-94fa-2215e7adb63b)

**Comment by MattDHill** [comment] 2024-01-10 02:13
Duplicate of https://github.com/Start9Labs/start-os/issues/2220

**Closed** 2024-01-10 02:13 UTC
Labels: Bug, Needs Triage
